INSERT INTO onlinestore.products (id, title, price, count) VALUES (45, 'SHARP E1', 20, 50);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (46, 'SONY 112', 15, 60);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (47, 'SHARP E3', 30, 40);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (48, 'SONY 121', 27, 30);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (49, 'SONY 125', 42, 70);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (50, 'SAMSUNG S70', 550, 45);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (51, 'LG #211    ', 600, 95);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (52, 'LG #212    ', 700, 22);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (53, 'SAMSUNG E70', 780, 25);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (54, 'SAMSUNG S20', 900, 45);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (55, 'JAVA   ', 30, 35);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (56, 'C++    ', 20, 45);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (57, 'MATLAB ', 30, 35);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (58, 'C#     ', 30, 35);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (59, 'FORTRAN', 30, 35);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (60, 'Magazine1', 10, 90);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (61, 'Magazine2', 11, 44);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (62, 'Magazine3', 19, 22);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (63, 'Magazine4', 21, 78);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (64, 'Magazine5', 17, 60);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (65, 'Gucci1', 100, 33);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (66, 'Gucci2', 185, 45);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (67, 'Gucci5', 215, 32);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (68, 'Armani', 303, 98);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (69, 'Armani', 190, 80);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (70, 'Adidas #21', 420, 143);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (71, 'Adidas #23', 220, 100);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (72, 'Nike  #221', 150, 170);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (73, 'Nike  #321', 265, 203);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (74, 'Puma #FE21', 130, 112);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (75, 'Adidas #21', 420, 143);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (76, 'Adidas #23', 220, 100);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (77, 'Nike  #221', 150, 170);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (78, 'Nike  #321', 265, 203);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (79, 'Puma #FE21', 130, 112);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (80, 'Adidas #21', 420, 143);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (81, 'Adidas #23', 220, 100);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (82, 'Nike  #221', 150, 170);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (83, 'Nike  #321', 265, 203);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (84, 'Puma #FE21', 130, 112);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (85, 'Adidas #21', 420, 143);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (86, 'Adidas #23', 220, 100);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (87, 'Nike  #221', 150, 170);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (88, 'Nike  #321', 265, 203);
INSERT INTO onlinestore.products (id, title, price, count) VALUES (89, 'Puma #FE21', 130, 112);